#version 450 core

layout(binding = 0, rgba8) uniform writeonly image3D destText;

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main()
{
	//ivec2 size = imageSize(destText);
	//ivec2 texelPos = ivec2(gl_GlobalInvocationID.xy);
	//imageStore(destText, ivec2(256, 256), vec4(0.0, 1.0, 0.0, 0.0));
	vec3 v = gl_GlobalInvocationID.xyz;
	imageStore(destText, ivec3(16,16,v.z), vec4(0.0, 1.0, v.z / 32.0, 0.0));
}